# Numpy Simulation

## Simulation of effect of NFQ Qulaification Level on Weekly Wages over 1, 3 and 5 years since graduation

#### What is NFQ Level:

#### Original Data from CSO study figure 6.4 

https://www.cso.ie/en/media/csoie/releasespublications/documents/education/2014/Higher_Education_Outcomes_book_-_web.pdf

Add figure 6.4

In [2]:
#import libraries
import matplotlib.pyplot as plt
import numpy as np
import pylab
Polynomial = np.polynomial.Polynomial
import matplotlib.patches as mpatches
import pandas as pd

In [8]:
#NFQ Level 6 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 245
NFQ6_1 = np.random.randint(240,250,(20,5))
print('Salaries Year1 NFQ6', NFQ6_1)

#100 samples looking to simulate mean value of 360
NFQ6_3 = np.random.randint(350,370,(20,5))
print('Salaries Year3 NFQ6', NFQ6_3)

#100 samples looking to simulate mean value of 475
NFQ6_5 = np.random.randint(470,480,(20,5))
print('Salries Year5 NFQ5', NFQ6_5)

Salaries Year1 NFQ6 [[247 248 242 243 248]
 [243 240 242 248 245]
 [241 248 248 243 249]
 [246 242 249 241 245]
 [248 245 249 244 242]
 [241 243 245 244 248]
 [241 243 243 243 240]
 [247 245 242 243 241]
 [249 242 249 249 248]
 [240 243 246 241 246]
 [247 249 240 249 249]
 [249 241 244 245 244]
 [240 249 240 247 242]
 [246 243 246 240 242]
 [249 242 242 242 247]
 [246 243 246 245 246]
 [249 246 244 244 246]
 [245 246 240 242 240]
 [247 243 241 245 240]
 [245 244 240 246 249]]
Salaries Year3 NFQ6 [[358 368 350 359 355]
 [361 355 359 368 359]
 [359 350 353 354 359]
 [365 365 368 359 351]
 [367 355 359 353 356]
 [356 353 350 365 357]
 [356 352 357 368 367]
 [355 351 360 356 354]
 [353 354 350 363 366]
 [360 365 364 358 369]
 [357 366 367 365 363]
 [358 365 350 351 362]
 [351 352 361 369 356]
 [358 359 361 353 360]
 [368 350 363 362 366]
 [355 359 359 351 364]
 [364 366 364 361 361]
 [367 362 363 362 358]
 [360 358 352 368 362]
 [362 360 358 353 367]]
Salries Year5 NFQ5 [[473 479 473 479 4