# Numpy Simulation

## Simulation of effect of NFQ Qulaification Level on Weekly Wages over 1, 3 and 5 years since graduation

#### What is NFQ Level:

#### Original Data from CSO study figure 6.4 

https://www.cso.ie/en/media/csoie/releasespublications/documents/education/2014/Higher_Education_Outcomes_book_-_web.pdf

Add figure 6.4

In [4]:
#import libraries
import matplotlib.pyplot as plt
import numpy as np
import pylab
Polynomial = np.polynomial.Polynomial
import matplotlib.patches as mpatches
import pandas as pd

In [5]:
#NFQ Level 6 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 245
NFQ6_1 = np.random.randint(240,250,(20,5))
print('Salaries Year1 NFQ6', NFQ6_1)

#100 samples looking to simulate mean value of 360
NFQ6_3 = np.random.randint(350,370,(20,5))
print('Salaries Year3 NFQ6', NFQ6_3)

#100 samples looking to simulate mean value of 475
NFQ6_5 = np.random.randint(470,480,(20,5))
print('Salries Year5 NFQ5', NFQ6_5)

Salaries Year1 NFQ6 [[242 248 247 243 242]
 [249 247 242 247 245]
 [246 243 246 246 246]
 [249 248 242 246 246]
 [249 249 240 243 243]
 [247 240 247 242 240]
 [242 246 242 243 245]
 [241 248 245 245 244]
 [247 243 241 246 249]
 [242 241 243 245 247]
 [241 246 242 249 242]
 [248 244 249 246 243]
 [245 240 243 249 241]
 [246 240 249 245 240]
 [241 241 245 242 240]
 [241 243 249 247 249]
 [245 243 249 245 246]
 [246 245 245 247 248]
 [243 240 240 243 246]
 [247 245 249 245 242]]
Salaries Year3 NFQ6 [[359 364 358 351 356]
 [353 358 350 356 361]
 [360 363 367 356 367]
 [364 364 364 355 355]
 [357 359 351 359 364]
 [362 353 367 357 366]
 [354 353 356 362 369]
 [356 360 351 354 359]
 [360 364 362 369 353]
 [360 355 367 353 362]
 [362 352 355 354 359]
 [366 367 352 351 364]
 [353 350 364 358 357]
 [363 362 354 354 367]
 [358 359 364 365 356]
 [357 357 359 363 360]
 [351 353 358 359 368]
 [362 361 369 366 353]
 [356 355 367 355 355]
 [353 359 361 352 351]]
Salries Year5 NFQ5 [[474 477 477 470 4

In [7]:
#NFQ Level 7 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 290
NFQ7_1 = np.random.randint(280,300,(20,5))
print('Salaries Year1 NFQ7', NFQ7_1)

#100 samples looking to simulate mean value of 420
NFQ7_3 = np.random.randint(410,430,(20,5))
print('Salaries Year3 NFQ7', NFQ7_3)

#100 samples looking to simulate mean value of 525
NFQ7_5 = np.random.randint(515,535,(20,5))
print('Salaries Year5 NFQ7', NFQ7_5)

Salaries Year1 NFQ7 [[290 293 295 282 290]
 [281 283 292 292 280]
 [280 283 280 291 292]
 [292 289 281 284 282]
 [299 299 281 289 299]
 [291 286 295 282 288]
 [290 293 284 297 296]
 [291 283 294 283 283]
 [280 297 281 288 298]
 [291 288 283 288 290]
 [289 293 289 296 294]
 [290 290 292 290 295]
 [284 297 292 299 290]
 [298 294 288 283 281]
 [295 291 295 281 283]
 [294 291 281 280 285]
 [297 288 282 297 281]
 [296 285 285 288 291]
 [282 298 297 283 284]
 [289 288 295 292 288]]
Salaries Year3 NFQ7 [[414 427 416 429 420]
 [424 417 425 415 412]
 [416 410 417 419 428]
 [424 426 411 423 421]
 [411 413 413 416 426]
 [411 412 420 421 428]
 [411 424 416 424 414]
 [415 420 428 420 419]
 [417 411 427 413 424]
 [413 422 417 420 423]
 [418 420 426 424 429]
 [423 426 426 414 412]
 [417 427 419 424 418]
 [422 422 411 424 410]
 [413 427 422 417 425]
 [426 418 411 429 426]
 [410 414 425 424 424]
 [429 423 418 425 411]
 [424 417 429 413 421]
 [415 414 424 427 411]]
Salaries Year5 NFQ7 [[526 525 516 524 