# Numpy Simulation

## Simulation of effect of NFQ Qulaification Level on Weekly Wages over 1, 3 and 5 years since graduation

#### What is NFQ Level:

#### Original Data from CSO study figure 6.4 

https://www.cso.ie/en/media/csoie/releasespublications/documents/education/2014/Higher_Education_Outcomes_book_-_web.pdf

Add figure 6.4

In [1]:
#import libraries
import matplotlib.pyplot as plt
import numpy as np
import pylab
Polynomial = np.polynomial.Polynomial
import matplotlib.patches as mpatches
import pandas as pd

In [2]:
#NFQ Level 6 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 245
NFQ6_1 = np.random.randint(240,250,(20,5))
print('Salaries Year1 NFQ6', NFQ6_1)

#100 samples looking to simulate mean value of 360
NFQ6_3 = np.random.randint(350,370,(20,5))
print('Salaries Year3 NFQ6', NFQ6_3)

#100 samples looking to simulate mean value of 475
NFQ6_5 = np.random.randint(470,480,(20,5))
print('Salries Year5 NFQ5', NFQ6_5)

Salaries Year1 NFQ6 [[247 243 240 248 243]
 [241 241 240 246 245]
 [242 247 241 247 243]
 [244 249 243 244 243]
 [247 248 242 244 240]
 [243 241 241 249 240]
 [244 247 248 240 243]
 [246 246 243 246 249]
 [244 242 246 246 249]
 [240 248 249 242 240]
 [241 247 240 247 244]
 [242 248 245 247 242]
 [245 249 245 249 247]
 [248 246 240 248 243]
 [242 246 240 245 242]
 [245 248 245 247 243]
 [244 244 243 245 249]
 [248 244 249 243 240]
 [245 241 245 244 245]
 [245 240 243 241 243]]
Salaries Year3 NFQ6 [[353 368 368 368 364]
 [356 369 356 360 357]
 [368 360 362 369 352]
 [350 362 368 365 351]
 [360 363 358 359 351]
 [353 355 360 353 358]
 [369 364 358 357 358]
 [365 360 357 369 356]
 [361 364 351 353 364]
 [358 352 367 351 361]
 [364 367 352 353 357]
 [353 359 357 362 351]
 [355 365 361 359 364]
 [355 365 369 358 358]
 [367 359 364 357 364]
 [355 361 367 354 353]
 [355 367 359 368 359]
 [366 358 357 368 358]
 [353 358 366 354 364]
 [367 362 354 358 364]]
Salries Year5 NFQ5 [[479 478 472 470 4

In [3]:
#NFQ Level 7 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 290
NFQ7_1 = np.random.randint(280,300,(20,5))
print('Salaries Year1 NFQ7', NFQ7_1)

#100 samples looking to simulate mean value of 420
NFQ7_3 = np.random.randint(410,430,(20,5))
print('Salaries Year3 NFQ7', NFQ7_3)

#100 samples looking to simulate mean value of 525
NFQ7_5 = np.random.randint(515,535,(20,5))
print('Salaries Year5 NFQ7', NFQ7_5)

Salaries Year1 NFQ7 [[287 282 281 291 293]
 [283 281 280 293 286]
 [280 281 291 295 298]
 [298 294 280 291 290]
 [291 289 290 297 298]
 [291 298 294 293 283]
 [286 296 285 286 298]
 [286 293 299 286 286]
 [297 296 291 297 283]
 [296 296 283 289 299]
 [281 286 294 282 294]
 [283 290 293 291 293]
 [288 284 287 288 284]
 [292 287 293 293 281]
 [288 298 291 282 284]
 [284 296 286 282 293]
 [291 282 285 299 288]
 [290 290 290 291 290]
 [292 291 295 297 286]
 [292 297 297 281 282]]
Salaries Year3 NFQ7 [[417 419 425 412 413]
 [429 412 424 424 410]
 [413 411 429 426 429]
 [415 419 421 410 422]
 [412 419 418 429 425]
 [415 419 421 417 421]
 [410 410 425 426 416]
 [420 419 410 425 427]
 [429 413 429 416 422]
 [429 428 429 428 424]
 [426 425 429 410 421]
 [427 421 428 410 423]
 [424 429 429 422 411]
 [428 421 421 428 427]
 [414 421 410 410 424]
 [420 412 411 429 415]
 [425 411 429 416 410]
 [412 429 411 426 422]
 [411 421 422 410 417]
 [427 426 419 419 417]]
Salaries Year5 NFQ7 [[534 527 521 516 

In [4]:
#NFQ Level 8 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 425
NFQ8_1 = np.random.randint(415,435,(20,5))
print('Salaries Year1 NFQ8', NFQ8_1)

#100 samples looking to simulate mean value of 535
NFQ8_3 = np.random.randint(525,545,(20,5))
print('Salaries Year3 NFQ8', NFQ8_3)

#100 samples looking to simulate mean value of 650
NFQ8_5 = np.random.randint(640,660,(20,5))
print('Salaries Year5 NFQ8', NFQ8_5)

Salaries Year1 NFQ8 [[429 425 423 420 433]
 [431 430 422 418 420]
 [421 417 417 428 420]
 [431 434 430 434 415]
 [421 425 430 431 422]
 [426 418 420 422 424]
 [419 428 423 416 427]
 [427 425 416 429 425]
 [424 417 433 427 432]
 [419 430 427 421 428]
 [426 431 424 433 434]
 [418 417 431 422 424]
 [420 424 417 423 434]
 [433 415 432 420 423]
 [419 420 433 426 425]
 [417 427 416 434 423]
 [417 425 419 428 423]
 [425 433 415 417 424]
 [418 417 419 426 425]
 [433 431 417 432 423]]
Salaries Year3 NFQ8 [[534 543 525 534 543]
 [533 538 542 537 532]
 [539 543 539 543 529]
 [542 539 530 531 527]
 [539 532 540 534 525]
 [534 541 535 529 531]
 [533 528 538 541 525]
 [525 538 535 537 540]
 [532 529 532 529 542]
 [538 525 539 532 539]
 [535 537 535 539 541]
 [538 531 538 525 526]
 [538 541 536 527 533]
 [543 526 542 535 535]
 [539 527 530 544 533]
 [534 541 530 525 540]
 [529 532 527 530 540]
 [533 539 537 532 542]
 [533 532 530 532 542]
 [530 537 544 525 537]]
Salaries Year5 NFQ8 [[656 647 653 652 

In [5]:
#NFQ Level 9 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 510
NFQ9_1 = np.random.randint(500,520,(20,5))
print('Salaries Year1 NFQ9', NFQ9_1)

#100 samples looking to simulate mean value of 630
NFQ9_3 = np.random.randint(620,640,(20,5))
print('Salaries Year3 NFQ9', NFQ9_3)

#100 samples looking to simulate mean value of 740
NFQ9_5 = np.random.randint(730,750,(20,5))
print('Salaries Year5 NFQ9', NFQ9_5)

Salaries Year1 NFQ9 [[513 508 503 508 507]
 [507 503 512 514 512]
 [519 508 516 518 502]
 [503 511 518 516 511]
 [511 502 518 515 507]
 [502 517 508 503 516]
 [504 500 503 512 508]
 [518 507 515 518 501]
 [512 517 511 519 500]
 [518 500 513 503 511]
 [503 517 515 513 518]
 [512 506 505 504 510]
 [515 508 517 517 519]
 [513 502 514 511 512]
 [515 516 515 506 513]
 [502 514 502 510 504]
 [504 503 516 505 512]
 [511 509 517 503 517]
 [500 504 506 519 505]
 [505 504 503 501 517]]
Salaries Year3 NFQ9 [[622 630 622 636 627]
 [637 633 624 625 621]
 [628 631 636 625 633]
 [627 635 636 637 625]
 [623 628 633 626 632]
 [630 620 631 620 634]
 [635 622 637 624 622]
 [622 639 627 626 624]
 [628 636 627 623 639]
 [631 628 636 625 632]
 [622 634 637 638 621]
 [636 625 623 638 625]
 [622 634 624 629 621]
 [637 631 621 639 630]
 [636 632 633 630 634]
 [624 627 637 633 634]
 [631 620 630 628 639]
 [630 636 620 636 630]
 [632 620 622 636 639]
 [625 621 635 628 632]]
Salaries Year5 NFQ9 [[731 736 738 746 

In [6]:
#NFQ Level 10 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 705
NFQ10_1 = np.random.randint(695,715,(20,5))
print('Salaries Year1 NFQ10', NFQ10_1)

#100 samples looking to simulate mean value of 805
NFQ10_3 = np.random.randint(795,815,(20,5))
print('Salaries Year3 NFQ10', NFQ10_3)

#100 samples looking to simulate mean value of 920
NFQ10_5 = np.random.randint(900,930,(20,5))
print('Salaries Year5 NFQ10', NFQ10_5)

Salaries Year1 NFQ10 [[711 710 696 710 712]
 [700 714 710 704 705]
 [703 711 696 701 709]
 [706 702 696 699 701]
 [706 711 699 704 702]
 [711 706 699 705 714]
 [701 713 696 697 711]
 [703 698 699 703 712]
 [710 705 700 697 714]
 [701 703 698 700 713]
 [699 705 696 708 704]
 [706 706 695 696 695]
 [713 700 696 700 713]
 [709 700 706 695 703]
 [706 709 705 709 698]
 [704 695 699 706 713]
 [700 711 711 707 714]
 [703 696 711 708 695]
 [699 695 711 708 701]
 [700 706 708 710 705]]
Salaries Year3 NFQ10 [[797 814 809 808 811]
 [799 801 802 795 807]
 [811 798 810 800 802]
 [803 803 796 806 813]
 [796 803 796 795 802]
 [813 805 810 808 802]
 [809 814 802 805 809]
 [804 800 810 810 797]
 [805 801 798 810 800]
 [799 799 797 799 799]
 [799 813 810 799 798]
 [808 801 806 800 813]
 [799 799 803 804 799]
 [802 796 805 803 801]
 [803 799 814 796 803]
 [797 811 798 811 803]
 [808 798 808 795 801]
 [801 799 801 807 804]
 [812 796 812 802 801]
 [801 797 813 812 810]]
Salaries Year5 NFQ10 [[900 929 924 9

In [10]:
#Calculate mean of weekly salaries for each qualification after 1, 3, 5 years after graduation

#NFQ level 6 after 1 year
x1 = np.mean(NFQ6_1)
print('Mean weekly wage of NFQ6 after 1 year is', x1)

#NFQ level 6 after 3 years
x2 = np.mean(NFQ6_3)
print('Mean weekly wage of NFQ6 after 3 years is', x2)

#NFQ level 6 after 5 years
x3 = np.mean(NFQ6_5)
print('Mean weekly wage of NFQ6 after 5 years is', x3)

Mean weekly wage of NFQ6 after 1 year is 244.37
Mean weekly wage of NFQ6 after 3 years is 359.91
Mean weekly wage of NFQ6 after 5 years is 474.45
