# Numpy Simulation

## Simulation of effect of NFQ Qulaification Level on Weekly Wages over 1, 3 and 5 years since graduation

#### What is NFQ Level:

#### Original Data from CSO study figure 6.4 

https://www.cso.ie/en/media/csoie/releasespublications/documents/education/2014/Higher_Education_Outcomes_book_-_web.pdf

Add figure 6.4

In [12]:
#import libraries
import matplotlib.pyplot as plt
import numpy as np
import pylab
Polynomial = np.polynomial.Polynomial
import matplotlib.patches as mpatches
import pandas as pd

In [13]:
#NFQ Level 6 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 245
NFQ6_1 = np.random.randint(240,250,(20,5))
print('Salaries Year1 NFQ6', NFQ6_1)

#100 samples looking to simulate mean value of 360
NFQ6_3 = np.random.randint(350,370,(20,5))
print('Salaries Year3 NFQ6', NFQ6_3)

#100 samples looking to simulate mean value of 475
NFQ6_5 = np.random.randint(470,480,(20,5))
print('Salries Year5 NFQ5', NFQ6_5)

Salaries Year1 NFQ6 [[243 240 244 240 248]
 [246 242 243 248 243]
 [241 247 243 245 247]
 [249 249 243 241 246]
 [248 243 242 244 247]
 [248 242 245 244 240]
 [242 245 248 240 244]
 [243 242 247 241 240]
 [241 241 248 241 249]
 [243 246 246 241 245]
 [240 245 249 243 243]
 [247 246 244 244 247]
 [248 243 243 241 247]
 [248 243 240 248 247]
 [240 249 245 245 248]
 [244 248 249 248 243]
 [249 244 241 242 246]
 [245 245 246 242 242]
 [241 247 242 247 241]
 [247 247 247 248 241]]
Salaries Year3 NFQ6 [[364 364 356 358 360]
 [361 355 363 363 364]
 [363 360 369 366 363]
 [352 362 356 368 367]
 [364 358 350 366 354]
 [355 363 362 357 358]
 [367 361 369 366 361]
 [351 359 364 362 357]
 [356 352 362 351 354]
 [360 358 350 359 360]
 [365 358 351 350 368]
 [359 368 360 367 357]
 [363 357 357 357 361]
 [369 365 359 352 352]
 [361 355 360 363 361]
 [369 356 357 353 364]
 [366 366 360 363 356]
 [365 358 350 356 368]
 [361 361 351 367 358]
 [359 366 363 368 356]]
Salries Year5 NFQ5 [[473 477 479 479 4

In [14]:
#NFQ Level 7 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 290
NFQ7_1 = np.random.randint(280,300,(20,5))
print('Salaries Year1 NFQ7', NFQ7_1)

#100 samples looking to simulate mean value of 420
NFQ7_3 = np.random.randint(410,430,(20,5))
print('Salaries Year3 NFQ7', NFQ7_3)

#100 samples looking to simulate mean value of 525
NFQ7_5 = np.random.randint(515,535,(20,5))
print('Salaries Year5 NFQ7', NFQ7_5)

Salaries Year1 NFQ7 [[294 283 296 284 294]
 [296 286 286 290 298]
 [281 297 295 282 292]
 [292 296 299 296 295]
 [291 289 290 289 285]
 [280 296 297 284 282]
 [283 293 294 284 291]
 [297 292 281 291 297]
 [296 288 294 281 285]
 [280 286 281 299 291]
 [299 295 289 281 299]
 [298 294 295 282 292]
 [296 280 282 280 290]
 [297 297 282 297 280]
 [290 288 289 292 291]
 [283 289 288 286 286]
 [287 291 293 281 294]
 [292 299 290 290 287]
 [284 298 286 295 292]
 [282 293 290 295 289]]
Salaries Year3 NFQ7 [[420 413 415 428 424]
 [425 416 419 425 410]
 [426 424 426 419 422]
 [414 426 415 421 418]
 [421 424 412 419 414]
 [417 428 423 416 412]
 [420 411 429 415 428]
 [419 412 426 417 414]
 [417 417 422 414 411]
 [423 429 416 426 416]
 [416 427 418 413 426]
 [428 411 421 422 420]
 [425 419 416 428 419]
 [410 419 418 423 414]
 [428 422 419 426 421]
 [421 415 421 412 413]
 [427 416 423 415 425]
 [414 420 414 419 424]
 [420 423 426 423 419]
 [422 422 414 417 428]]
Salaries Year5 NFQ7 [[534 516 523 530 

In [15]:
#NFQ Level 8 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 425
NFQ8_1 = np.random.randint(415,435,(20,5))
print('Salaries Year1 NFQ8', NFQ8_1)

#100 samples looking to simulate mean value of 535
NFQ8_3 = np.random.randint(525,545,(20,5))
print('Salaries Year3 NFQ8', NFQ8_3)

#100 samples looking to simulate mean value of 650
NFQ8_5 = np.random.randint(640,660,(20,5))
print('Salaries Year5 NFQ8', NFQ8_5)

Salaries Year1 NFQ8 [[417 417 434 424 426]
 [433 434 431 428 433]
 [419 422 425 417 427]
 [430 427 425 427 418]
 [427 428 427 419 415]
 [425 416 415 415 427]
 [429 419 430 427 420]
 [420 425 423 418 419]
 [418 434 423 417 420]
 [421 424 419 418 429]
 [417 428 427 418 429]
 [418 431 417 415 420]
 [426 425 419 416 427]
 [426 419 419 428 426]
 [416 424 427 433 423]
 [422 418 426 431 425]
 [431 427 424 421 429]
 [427 423 432 433 428]
 [427 425 430 416 421]
 [426 415 416 420 417]]
Salaries Year3 NFQ8 [[539 533 526 539 527]
 [536 536 535 527 540]
 [538 536 526 540 525]
 [543 544 542 542 538]
 [533 543 542 540 529]
 [544 537 529 528 544]
 [539 541 542 530 531]
 [531 538 544 537 543]
 [533 537 538 542 533]
 [526 529 528 528 528]
 [544 538 529 537 540]
 [525 539 526 528 532]
 [532 536 529 540 525]
 [534 533 532 525 526]
 [532 531 530 531 539]
 [536 526 532 526 541]
 [533 526 526 527 535]
 [544 539 535 536 543]
 [528 529 537 527 533]
 [532 536 543 532 532]]
Salaries Year5 NFQ8 [[651 659 654 646 

In [16]:
#NFQ Level 9 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 510
NFQ9_1 = np.random.randint(500,520,(20,5))
print('Salaries Year1 NFQ9', NFQ9_1)

#100 samples looking to simulate mean value of 630
NFQ9_3 = np.random.randint(620,640,(20,5))
print('Salaries Year3 NFQ9', NFQ9_3)

#100 samples looking to simulate mean value of 740
NFQ9_5 = np.random.randint(730,750,(20,5))
print('Salaries Year5 NFQ9', NFQ9_5)

Salaries Year1 NFQ9 [[508 501 514 506 513]
 [517 510 511 514 501]
 [513 500 504 500 515]
 [514 511 507 511 513]
 [501 515 514 509 503]
 [503 508 508 519 512]
 [508 503 507 506 505]
 [517 517 500 504 511]
 [503 519 519 512 505]
 [510 507 502 506 510]
 [503 511 500 517 504]
 [517 516 514 500 509]
 [507 502 507 510 513]
 [500 506 511 512 517]
 [505 519 506 519 513]
 [508 514 506 507 516]
 [511 514 500 514 500]
 [517 515 500 511 510]
 [500 519 500 509 503]
 [501 507 508 514 505]]
Salaries Year3 NFQ9 [[621 630 622 624 623]
 [626 633 634 622 620]
 [621 631 628 622 635]
 [621 620 620 622 627]
 [629 631 638 624 633]
 [631 622 623 630 629]
 [625 624 633 626 636]
 [630 621 630 639 623]
 [621 622 638 639 620]
 [622 628 621 623 623]
 [630 639 624 625 625]
 [623 635 622 638 635]
 [623 633 621 630 628]
 [634 628 635 638 620]
 [628 629 620 634 630]
 [621 629 623 632 638]
 [633 621 620 634 628]
 [620 625 637 638 623]
 [629 630 638 632 625]
 [637 636 623 630 638]]
Salaries Year5 NFQ9 [[740 732 735 732 

In [17]:
#NFQ Level 10 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 705
NFQ10_1 = np.random.randint(695,715,(20,5))
print('Salaries Year1 NFQ10', NFQ10_1)

#100 samples looking to simulate mean value of 805
NFQ10_3 = np.random.randint(795,815,(20,5))
print('Salaries Year3 NFQ10', NFQ10_3)

#100 samples looking to simulate mean value of 920
NFQ10_5 = np.random.randint(900,930,(20,5))
print('Salaries Year5 NFQ10', NFQ10_5)

Salaries Year1 NFQ10 [[705 698 709 705 697]
 [708 696 712 700 710]
 [711 704 707 707 697]
 [705 702 702 701 702]
 [706 698 713 697 709]
 [696 712 712 705 701]
 [697 708 712 701 708]
 [698 706 707 695 709]
 [704 701 704 695 708]
 [701 697 698 695 695]
 [699 700 712 705 695]
 [711 712 712 705 714]
 [713 714 702 699 709]
 [695 706 708 699 712]
 [700 704 699 702 713]
 [701 712 704 712 712]
 [710 697 709 707 714]
 [711 697 708 695 708]
 [704 705 711 713 709]
 [705 700 713 711 710]]
Salaries Year3 NFQ10 [[799 805 798 806 810]
 [807 801 807 804 806]
 [809 802 803 796 812]
 [801 810 804 802 807]
 [809 804 813 812 801]
 [803 805 812 810 807]
 [811 808 805 798 812]
 [801 813 807 807 810]
 [805 805 798 804 810]
 [802 802 795 796 812]
 [801 808 806 814 812]
 [806 803 799 813 800]
 [796 797 806 804 802]
 [803 813 803 799 806]
 [806 806 803 805 800]
 [807 808 802 798 804]
 [810 803 797 795 804]
 [801 801 800 804 802]
 [813 802 806 808 808]
 [800 795 797 805 810]]
Salaries Year5 NFQ10 [[910 919 918 9