# Numpy Simulation

## Simulation of effect of NFQ Qulaification Level on Weekly Wages over 1, 3 and 5 years since graduation

#### What is NFQ Level:

#### Original Data from CSO study figure 6.4 

https://www.cso.ie/en/media/csoie/releasespublications/documents/education/2014/Higher_Education_Outcomes_book_-_web.pdf

Add figure 6.4

In [15]:
#import libraries
import matplotlib.pyplot as plt
import numpy as np
import pylab
Polynomial = np.polynomial.Polynomial
import matplotlib.patches as mpatches
import pandas as pd

In [16]:
#NFQ Level 6 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 245
NFQ6_1 = np.random.randint(240,250,(20,5))
print('Salaries Year1 NFQ6', NFQ6_1)

#100 samples looking to simulate mean value of 360
NFQ6_3 = np.random.randint(350,370,(20,5))
print('Salaries Year3 NFQ6', NFQ6_3)

#100 samples looking to simulate mean value of 475
NFQ6_5 = np.random.randint(470,480,(20,5))
print('Salries Year5 NFQ5', NFQ6_5)

Salaries Year1 NFQ6 [[243 241 246 245 247]
 [242 240 246 245 240]
 [242 241 242 246 247]
 [247 241 245 248 240]
 [248 247 246 245 248]
 [243 249 249 248 249]
 [240 242 243 245 245]
 [244 241 248 247 242]
 [242 245 246 246 247]
 [246 248 242 249 246]
 [249 240 245 245 240]
 [242 240 249 248 243]
 [241 243 248 240 243]
 [243 242 243 244 241]
 [247 244 242 242 240]
 [249 247 247 248 241]
 [248 247 243 244 240]
 [241 241 249 247 245]
 [247 240 247 241 241]
 [242 242 246 244 246]]
Salaries Year3 NFQ6 [[365 359 354 355 366]
 [354 369 358 350 356]
 [357 369 352 365 355]
 [354 364 367 357 352]
 [353 359 354 359 355]
 [360 368 358 353 369]
 [359 352 359 353 354]
 [366 359 369 353 368]
 [353 363 363 354 353]
 [353 369 355 351 364]
 [364 358 355 361 360]
 [359 351 364 367 353]
 [354 366 362 369 364]
 [367 364 355 369 364]
 [360 355 351 357 366]
 [363 367 350 366 358]
 [364 353 367 357 350]
 [352 360 358 355 358]
 [350 356 359 351 357]
 [366 368 360 369 355]]
Salries Year5 NFQ5 [[471 478 470 479 4

In [17]:
#NFQ Level 7 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 290
NFQ7_1 = np.random.randint(280,300,(20,5))
print('Salaries Year1 NFQ7', NFQ7_1)

#100 samples looking to simulate mean value of 420
NFQ7_3 = np.random.randint(410,430,(20,5))
print('Salaries Year3 NFQ7', NFQ7_3)

#100 samples looking to simulate mean value of 525
NFQ7_5 = np.random.randint(515,535,(20,5))
print('Salaries Year5 NFQ7', NFQ7_5)

Salaries Year1 NFQ7 [[285 295 292 298 283]
 [291 294 292 284 285]
 [289 290 283 287 287]
 [297 283 299 280 289]
 [296 280 283 299 287]
 [298 291 281 285 282]
 [283 298 284 298 283]
 [280 292 280 297 285]
 [289 293 281 299 281]
 [285 296 280 297 295]
 [297 290 289 281 290]
 [293 290 296 294 298]
 [290 295 283 282 282]
 [282 288 294 290 297]
 [289 284 293 297 284]
 [291 299 297 291 292]
 [289 299 294 286 289]
 [295 288 282 291 288]
 [297 293 286 291 294]
 [286 282 285 284 296]]
Salaries Year3 NFQ7 [[425 424 416 428 421]
 [410 416 415 425 419]
 [411 425 421 426 421]
 [427 418 412 429 429]
 [412 426 420 422 411]
 [419 429 411 413 414]
 [411 413 429 420 412]
 [427 423 428 425 427]
 [428 419 417 423 419]
 [421 418 422 427 424]
 [419 417 429 420 423]
 [421 419 424 424 422]
 [414 427 419 416 424]
 [428 426 422 419 417]
 [415 417 427 425 415]
 [421 416 414 410 421]
 [417 428 428 424 411]
 [422 419 414 429 412]
 [425 427 422 417 415]
 [420 426 426 424 429]]
Salaries Year5 NFQ7 [[532 525 531 516 

In [18]:
#NFQ Level 8 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 425
NFQ8_1 = np.random.randint(415,435,(20,5))
print('Salaries Year1 NFQ8', NFQ8_1)

#100 samples looking to simulate mean value of 535
NFQ8_3 = np.random.randint(525,545,(20,5))
print('Salaries Year3 NFQ8', NFQ8_3)

#100 samples looking to simulate mean value of 650
NFQ8_5 = np.random.randint(640,660,(20,5))
print('Salaries Year5 NFQ8', NFQ8_5)

Salaries Year1 NFQ8 [[422 427 434 429 434]
 [434 419 429 424 429]
 [432 423 433 431 425]
 [428 428 422 431 422]
 [430 430 424 425 421]
 [426 429 430 417 419]
 [428 424 427 420 417]
 [430 422 424 421 420]
 [417 421 422 433 417]
 [423 429 423 416 427]
 [418 426 434 426 427]
 [419 423 428 421 420]
 [423 427 419 421 423]
 [421 423 431 431 416]
 [432 425 431 420 425]
 [420 418 433 433 429]
 [420 430 427 420 424]
 [419 422 434 427 415]
 [418 420 425 420 430]
 [433 431 430 420 424]]
Salaries Year3 NFQ8 [[544 539 526 540 532]
 [540 529 542 525 544]
 [535 534 535 525 531]
 [532 527 540 543 540]
 [541 544 544 528 539]
 [537 526 542 540 539]
 [541 526 543 537 532]
 [542 530 543 538 539]
 [535 534 538 537 534]
 [527 533 538 544 540]
 [526 532 534 537 531]
 [527 536 536 527 544]
 [525 542 537 535 529]
 [538 534 530 529 533]
 [543 526 537 537 537]
 [525 536 540 544 536]
 [541 532 534 529 538]
 [536 528 536 530 529]
 [537 527 538 525 541]
 [540 526 543 535 541]]
Salaries Year5 NFQ8 [[640 640 651 643 

In [19]:
#NFQ Level 9 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 510
NFQ9_1 = np.random.randint(500,520,(20,5))
print('Salaries Year1 NFQ9', NFQ9_1)

#100 samples looking to simulate mean value of 630
NFQ9_3 = np.random.randint(620,640,(20,5))
print('Salaries Year3 NFQ9', NFQ9_3)

#100 samples looking to simulate mean value of 740
NFQ9_5 = np.random.randint(730,750,(20,5))
print('Salaries Year5 NFQ9', NFQ9_5)

Salaries Year1 NFQ9 [[519 516 512 507 510]
 [514 512 517 514 514]
 [506 502 519 504 517]
 [502 503 504 506 505]
 [506 515 508 504 513]
 [517 504 510 516 511]
 [516 513 506 504 516]
 [510 510 508 504 500]
 [505 508 502 519 509]
 [507 515 506 513 504]
 [502 500 515 513 511]
 [518 508 506 510 519]
 [510 510 518 513 502]
 [513 515 502 507 517]
 [512 518 507 516 511]
 [510 514 507 503 518]
 [509 511 505 509 517]
 [516 503 506 517 511]
 [516 507 515 501 511]
 [504 516 513 506 506]]
Salaries Year3 NFQ9 [[634 639 638 624 629]
 [638 625 628 626 634]
 [633 631 631 623 633]
 [631 622 622 635 639]
 [634 631 625 634 628]
 [628 627 627 637 637]
 [630 630 637 622 626]
 [624 626 628 633 636]
 [635 631 628 631 621]
 [629 623 622 628 625]
 [629 622 624 631 623]
 [629 629 631 626 628]
 [623 620 622 620 622]
 [622 626 631 626 626]
 [624 637 638 621 626]
 [627 638 636 635 634]
 [638 639 634 637 632]
 [638 639 628 623 636]
 [628 620 635 626 626]
 [636 637 623 634 628]]
Salaries Year5 NFQ9 [[739 731 733 740 

In [20]:
#NFQ Level 10 and weekly salary after 1, 3, 5 years, use randint that has discrete uniform distribution. 100 Datapoints

#100 samples looking to simulate mean value of 705
NFQ10_1 = np.random.randint(695,715,(20,5))
print('Salaries Year1 NFQ10', NFQ10_1)

#100 samples looking to simulate mean value of 805
NFQ10_3 = np.random.randint(795,815,(20,5))
print('Salaries Year3 NFQ10', NFQ10_3)

#100 samples looking to simulate mean value of 920
NFQ10_5 = np.random.randint(910,930,(20,5))
print('Salaries Year5 NFQ10', NFQ10_5)

Salaries Year1 NFQ10 [[714 695 700 712 706]
 [701 698 712 702 707]
 [702 696 703 704 702]
 [707 706 706 696 699]
 [708 709 706 704 702]
 [709 705 704 699 704]
 [712 708 701 710 696]
 [697 698 705 709 702]
 [697 710 712 714 702]
 [701 695 702 704 701]
 [712 703 706 707 699]
 [709 699 710 699 700]
 [710 707 713 707 713]
 [703 711 712 711 696]
 [700 710 708 710 702]
 [696 702 701 701 707]
 [695 699 711 711 699]
 [706 709 713 701 711]
 [703 701 703 713 710]
 [698 710 699 695 699]]
Salaries Year3 NFQ10 [[808 813 801 808 801]
 [799 810 809 796 811]
 [806 806 807 811 805]
 [799 799 808 797 799]
 [800 814 807 798 803]
 [797 796 797 812 806]
 [797 801 807 809 811]
 [814 801 807 812 805]
 [814 796 803 810 805]
 [804 802 805 801 809]
 [814 804 799 798 811]
 [803 796 798 799 799]
 [796 809 805 810 805]
 [810 800 809 802 796]
 [802 813 801 799 798]
 [811 800 797 811 796]
 [807 797 806 800 810]
 [796 795 804 811 798]
 [806 813 813 814 813]
 [805 805 801 808 801]]
Salaries Year5 NFQ10 [[910 917 910 9

In [21]:
#Calculate mean of weekly salaries for each qualification after 1, 3, 5 years after graduation

#NFQ level 6 after 1 year
x1 = np.mean(NFQ6_1)
print('Mean weekly wage of NFQ6 after 1 year is', x1)

#NFQ level 6 after 3 years
x2 = np.mean(NFQ6_3)
print('Mean weekly wage of NFQ6 after 3 years is', x2)

#NFQ level 6 after 5 years
x3 = np.mean(NFQ6_5)
print('Mean weekly wage of NFQ6 after 5 years is', x3)

Mean weekly wage of NFQ6 after 1 year is 244.37
Mean weekly wage of NFQ6 after 3 years is 359.2
Mean weekly wage of NFQ6 after 5 years is 474.67


In [22]:
#NFQ level 7 after 1 year
x4 = np.mean(NFQ7_1)
print('Mean weekly wage of NFQ7 after 1 year is', x4)

#NFQ level 7 after 3 years
x5 = np.mean(NFQ7_3)
print('Mean weekly wage of NFQ7 after 3 years is', x5)

#NFQ level 7 after 5 years
x6 = np.mean(NFQ7_5)
print('Mean weekly wage of NFQ7 after 5 years is', x6)

Mean weekly wage of NFQ7 after 1 year is 289.54
Mean weekly wage of NFQ7 after 3 years is 420.74
Mean weekly wage of NFQ7 after 5 years is 524.72


In [23]:
#NFQ level 8 after 1 year
x7 = np.mean(NFQ8_1)
print('Mean weekly wage of NFQ8 after 1 year is', x7)

#NFQ level 8 after 3 years
x8 = np.mean(NFQ8_3)
print('Mean weekly wage of NFQ8 after 3 years is', x8)

#NFQ level 8 after 5 years
x9 = np.mean(NFQ8_5)
print('Mean weekly wage of NFQ8 after 5 years is', x9)

Mean weekly wage of NFQ8 after 1 year is 425.0
Mean weekly wage of NFQ8 after 3 years is 535.23
Mean weekly wage of NFQ8 after 5 years is 649.19


In [24]:
#NFQ level 9 after 1 year
x10 = np.mean(NFQ9_1)
print('Mean weekly wage of NFQ9 after 1 year is', x10)

#NFQ level 9 after 3 years
x11 = np.mean(NFQ9_3)
print('Mean weekly wage of NFQ9 after 3 years is', x11)

#NFQ level 9 after 5 years
x12 = np.mean(NFQ9_5)
print('Mean weekly wage of NFQ9 after 5 years is', x12)

Mean weekly wage of NFQ9 after 1 year is 510.06
Mean weekly wage of NFQ9 after 3 years is 629.51
Mean weekly wage of NFQ9 after 5 years is 738.91


In [25]:
#NFQ level 10 after 1 year
x13 = np.mean(NFQ10_1)
print('Mean weekly wage of NFQ10 after 1 year is', x13)

#NFQ level 10 after 3 years
x14 = np.mean(NFQ10_3)
print('Mean weekly wage of NFQ10 after 3 years is', x14)

#NFQ level 10 after 5 years
x15 = np.mean(NFQ10_5)
print('Mean weekly wage of NFQ10 after 5 years is', x15)

Mean weekly wage of NFQ10 after 1 year is 704.44
Mean weekly wage of NFQ10 after 3 years is 804.3
Mean weekly wage of NFQ10 after 5 years is 919.46
